{% set setup_data = load_setup_py_data() %}

package:
  name: conda-verify
  version: {{ setup_data["version"] }}

source:
  path: ../

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps
  noarch: python
  skip:  True  # [py27]

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - jinja2
    - click
    - pyyaml
    - future
    - backports.functools_lru_cache  # [py<33]
    - backports.tempfile
    - conda-package-handling >=1.0.4
    - six
    - tqdm
    - py-lief

test:
  imports:
    - conda_verify
  commands:
    # return code of version and help is 1 on windows !?
    - conda-verify --version  # [unix]
    - conda-verify --help     # [unix]

about:
  home: https://github.com/conda/conda-verify
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: tool for validating conda recipes and conda packages
  description: |
    conda-verify is a tool for (passively) verifying conda recipes and conda
    packages.

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - mwcraig
    - ocefpaf
    - patricksnape
    - pelson
    - scopatz
    - mandeep
