{% set setup_data = load_setup_py_data() %}

package:
  name: conda-verify
  version: {{ setup_data['version'] }}

source:
  path: ../

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - jinja2
    - click
    - pyyaml
    - future
    - backports.functools_lru_cache  # [py<33]
    - python-libarchive-c

build:
  script: pip install . --no-deps

test:
  imports:
    - conda_verify
  commands:
    - conda-verify --version
    - conda-verify --help

about:
  home: https://github.com/conda/conda-verify
  license: BSD
  license_file: LICENSE.txt
